### ISSUE TITLE
Incorrect exit code from `stop()` in init.d script on RPM

### ISSUE THREAD

**Issue by seancribbs** [basho/node_package#104]
See basho/puppet-riak#25 for details. tl;dr `RETVAL` is not reassigned to `0` after usage.

**Comment by jaredmorrow** [comment]
This was fixed after the 1.4.2 release of riak, which used `1.3.4` of node_package.   The fix is here: https://github.com/basho/node_package/commit/0c405da5083040b34da7162ee7f4583b30f3c27d

**Comment by L2G** [comment]
Will the RPMs hosted at yum.basho.com be rebuilt with this fix?

**Comment by jaredmorrow** [comment]
It will be caught in the 1.4.4 and 2.0 packages when they are released.
