### ISSUE TITLE
Incorrect start using SSL for Erlang Distribution

### ISSUE THREAD

**Issue by mikhailigonin** [basho/node_package#107]
Guys, please help - i'm using node_package to build my application, and defined an environment variables in the file vm.ags as described http://www.erlang.org/doc/apps/ssl/ssl_distribution.html:
-proto_dist inet_tls
-ssl_dist_opt client_certfile "/var/lib/myapp/cert.pem"
-ssl_dist_opt server_certfile "/var/lib/myapp/cert.pem"
-ssl_dist_opt server_secure_renegotiate true
-ssl_dist_opt client_secure_renegotiate true

And then run:
[root@srv bin]# myapp start
!!!!
!!!! WARNING: ulimit -n is 1024; 4096 is the recommended minimum.
!!!!
myapp failed to start within 15 seconds,
see the output of 'myapp console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

At the same process beam.smp is alive (!), but all commands do not work (stop/attach/getpig, etc.).
myapp console -- works correctly...

It is not clear is this a bug, or it is my mistake?

**Comment by jaredmorrow** [comment]
What do the console / error logs say?  There might be another problem unrelated to SSL.

**Comment by mikhailigonin** [comment]
In the console log -- all well, as if the node is started correctly.
The error log is empty.
The 'ps eax | grep beam.smp' command -- shows, that the Erlang virtual machine is running.
But:
- Command 'start' -- hangs
- The node cannot be stopped, because the 'stop' command does not work
- I can't connect to the node through 'attach'/'attach-direct' for the same reason
- Even 'getpid' says that the node is not running. But really -- it works )

**Comment by jaredmorrow** [comment]
So the best move forward is to run 'console' so that all output is seen.  If that doesn't give you a clue, you will need to run the commands that 'console' is running by hand (like the `nodetool` calls) until you find the issue.  Unfortunately I've done this many times and it is tedious, but it will usually find what is actually failing.  Sorry for the troubles.
