### ISSUE TITLE
Source /etc/sysconfig/riak in RHEL init script like Debian/Ubuntu

### ISSUE THREAD

**Issue by hectcastro** [basho/node_package#114]
The init scripts for Debian/Ubuntu source `/etc/default/riak`, which is an easy way to do things like set `ulimit` for Riak.

Is there a reason the RHEL based init scripts don't source something like `/etc/sysconfig/riak`? Would there be any downsides to adding that?

**Comment by jaredmorrow** [comment]
No reason they can't do that.

**Comment by jaredmorrow** [comment]
Fixed in #116
