### ISSUE TITLE
Check for valid shell for riak user

### ISSUE THREAD

**Issue by cheeseplus** [basho/node_package#122]
Reported by a user:

"Hey guys, I figured this out. We just recently went through a PCI audit, and as part of that the auditors had us change the shell for all non-login users to `/bin/false`. Riak (at least the version we're running!) is not at all amused by that apparently."

**Comment by jaredmorrow** [comment]
That's correct, it needs a shell to set up the environment to run erlang.
 I've been bit by attempting to change the shell in the past. B

**Comment by jaredmorrow** [comment]
This will not be fixed as we need a shell to run erlang after being dropped into the riak user.
