### ISSUE TITLE
Some small issues with `su` replacement

### ISSUE THREAD

**Issue by lukebakken** [basho/node_package#130]
Related to #125 and #72 

FreeBSD 9.2 test VM:
- `riak` command can be run to get usage without `sudo`, `riak-admin` cannot:
  
  ```
  $ riak
  Usage: riak «command»
  where «command» is one of the following:
      { help | start | stop | restart | reboot | ping | console | attach
      attach-direct | ertspath | chkconfig | escript | version | getpid
      top [-interval N] [-sort { reductions | memory | msg_q }] [-lines N] } |
      config { generate | effective | describe VARIABLE } [-l debug]
  
  Run `riak help` for more detailed information.
  
  $ riak-admin
  You need to be root or use sudo to run this command
  ```
- `riak ping` requires `sudo` (fixed already I believe)

**Comment by Vagabond** [comment]
Jared and I discussed the riak-admin thing, but since riak-admin can ONLY be run with superuser privs (or as the riak user) anyway, we decided it wasn't terribly interesting to print the usage message.

**Comment by lukebakken** [comment]
OK!
