### ISSUE TITLE
"riak reboot" does not reboot Riak

### ISSUE THREAD

**Issue by lukebakken** [basho/node_package#131]
Testing a 2.0 build with the `sudo` -> `su` changes on a single node, it appears that `riak reboot` does not restart Riak as the command help and docs would indicate:

```
vagrant@DEBIAN-7-YZTEST:~$ sudo /usr/sbin/riak reboot
ok
vagrant@DEBIAN-7-YZTEST:~$ sudo /usr/sbin/riak ping
Node 'riak@127.0.0.1' not responding to pings.
```

**Comment by jrwest** [comment]
I don't believe this worked before either. @lordnull I think you verified that?

**Comment by lordnull** [comment]
By default it doesn't seem to work, because by default the erlang heartbeat functionality is not enabled. If that was enabled (in the old style vm args) it should restart. However, even the otp distribution makes no hard guarantee about it.

**Comment by jrwest** [comment]
Sounds like a candidate for removal

**Comment by lukebakken** [comment]
Along with "restart" :smile:

**Comment by jaredmorrow** [comment]
This has come up several times, I'll have to dig up the last email thread.  I don't dare risk removing anything else before beta, and `restart` needs to be there, so maybe we can fix that if it is broken.  I agree reboot should go away.

**Comment by lukebakken** [comment]
I'll do some restart testing. FYI the general CSE advice at the moment is "don't use restart, use stop/start"

**Comment by jrwest** [comment]
@jaredmorrow restart needs to be there because packages or something assume/require it, or that was the opinion at the time?

**Comment by jaredmorrow** [comment]
Yes that's the reason we wanted restart.

**Comment by jrwest** [comment]
ok, probably a call for @jonmeredith but I'd vote for fixing `restart` and removing `reboot`.

**Comment by lukebakken** [comment]
I'm not sure how much fixing there is to be done for `init:restart/0` as it's a VM function.

**Comment by jaredmorrow** [comment]
Well init:restart/0 used to work, but I wonder if our longer startup and shutdown is just too much for that poor little function.  If we just wanted the functionality of the command line we can have it call stop and start in sequence, but the point of it was to restart riak without exiting out of the VM.

**Comment by lukebakken** [comment]
:+1: to stop/start behind the scenes ... I think your theory about restart is correct. In addition, stopping the process / starting it clears up sockets, memory, etc. I don't know how `init:restart` interacts with leveldb/bitcask (NIF) either.

**Comment by jaredmorrow** [comment]
For reference the only package that calls 'riak restart' is debian in a
'reload' function that people expect to not do a full restart.  I'd rather
have something that works over something just trying to square peg in a
round hole.

**Comment by lukebakken** [comment]
Unfortunately, we have people running `riak restart` from the command line... and it doesn't always leave things in a good state.

**Comment by jaredmorrow** [comment]
Agreed.  I'm happy to make the change, just want either Jon or a PM to
chime in.

**Comment by jaredmorrow** [comment]
Removed reboot

**Comment by lukebakken** [comment]
@jaredmorrow - thanks. Any word on the future of `riak restart` ?

**Comment by jaredmorrow** [comment]
I'll rework 'restart' post-beta as a bug fix for RC.  Restart does work on fast machines with little data, but times out when startup takes too long.

**Comment by lukebakken** [comment]
Thanks for the info @jaredmorrow

**Comment by macintux** [comment]
@jaredmorrow is this still something you're planning for RC?

**Comment by jaredmorrow** [comment]
I'm going to try and get to it, it keeps getting pushed to the bottom of the pile.
