### ISSUE TITLE
erlexec: HOME must be set

### ISSUE THREAD

**Issue by hectcastro** [basho/node_package#135]
Using the `service` command to interact with the Riak 2.0.0beta1 `init.d` script a Ubuntu 12.04 box yields:

``` bash
vagrant@enterprise-ubuntu-1204:~$ sudo service riak status
erlexec: HOME must be set
riak is stopped
vagrant@enterprise-ubuntu-1204:~$ sudo service riak ping
erlexec: HOME must be set
```

If I run the same commands against the `/etc/init.d/riak` script, I get:

``` bash
vagrant@enterprise-ubuntu-1204:~$ sudo /etc/init.d/riak status
pong
riak is running
vagrant@enterprise-ubuntu-1204:~$ sudo /etc/init.d/riak ping
pong
```

It appears that the `service` command wipes out environmental variables. If I add an export for `HOME` to the `init.d` script:

``` bash
vagrant@enterprise-ubuntu-1204:~$ diff /etc/init.d/riak /etc/init.d/riak.bak
12,13d11
< export HOME=/var/lib/riak
<
```

Everything works as expected:

``` bash
vagrant@enterprise-ubuntu-1204:~$ sudo service riak status
pong
riak is running
vagrant@enterprise-ubuntu-1204:~$ sudo service riak ping
pong
```

**Comment by Vagabond** [comment]
We should probably figure out what environment vars, in general, need to be set. We could simplify our 'su' usage if we didn't have to emulate a login session to get the right ENV vars set up.

**Comment by jaredmorrow** [comment]
I have another node_package bug I'm testing today, so if anyone else can
take this one before beta2 that'd be great.  If not I'll try to get to it
later this week.

**Comment by jaredmorrow** [comment]
I just saw this issue on Ubuntu 14.04 as well.  This is for sure a must-fix for RC.

**Comment by jaredmorrow** [comment]
Will be fixed in beta2.
