### ISSUE TITLE
Clarify `log_daemon_msg` in Debian init.script

### ISSUE THREAD

**Issue by jcapricebasho** [basho/node_package#144]
the log_daemon_msg messages, when output, are a bit difficult to read.

For example, the restart message:

```
log_daemon_msg "Restarting $DESC" "$NAME"
```

outputs: "Restarting Riak is a distributed data store riak"

The description can be left out, or added to the end like: "Restarting riak." or "Restarting riak. Riak is a distributed data store." for better readability.

**Comment by jaredmorrow** [comment]
Fixed on develop

**Comment by jaredmorrow** [comment]
New text

```
vagrant@precise64:~$ sudo /etc/init.d/riak restart
 * Restarting riak
```
