### ISSUE TITLE
Help text for chkconfig is broken

### ISSUE THREAD

**Issue by macintux** [basho/node_package#147]
This is the output from `riak help`:

```
    chkconfig
        Confirms whether the app.config is valid.

        For applications configured with cuttlefish, this includes a call
        to  also
```

The missing text between "to" and "also" is "config generate"; it probably should also be explicit that it checks both `riak.conf` and `advanced.config`.

**Comment by jaredmorrow** [comment]
If you change it make sure it is <package_name>.conf since node_package is
not Riak specific.
