### ISSUE TITLE
Issues with FreeBSD 10 - 2.0.0rc1 package

### ISSUE THREAD

**Issue by lukebakken** [basho/node_package#150]
Package installed: `riak-2.0.0rc1.txz`

On start, this error is generated in `/var/log/riak/solr.log`:

```
        at org.eclipse.jetty.start.Main.start(Main.java:615)
        at org.eclipse.jetty.start.Main.main(Main.java:96)
Caused by: java.lang.IllegalArgumentException: Bad temp directory: /usr/local/lib/riak/lib/yokozuna-2.0.0beta1-81-g47214a6/priv/solr/solr-webapp
        at org.eclipse.jetty.webapp.WebAppContext.setTempDirectory(WebAppContext.java:1129)
        ... 41 more
```

To resolve, create the directory _and_ set `riak:riak` as the owner of `/usr/local/lib/riak` and subdirectories (`root:wheel` on the install):

```
mkdir /usr/local/lib/riak/lib/yokozuna-2.0.0beta1-81-g47214a6/priv/solr/solr-webapp
chown -R riak:riak /usr/local/lib/riak
```

**Comment by lukebakken** [comment]
FYI the `mkdir` step isn't necessary as Solr creates the directory on start. It's just a permissions issue.

**Comment by lukebakken** [comment]
I'm looking into redirecting that temp directory to `platform_data_dir`

**Comment by jaredmorrow** [comment]
Hmm, this was supposed to be fixed here: https://github.com/basho/node_package/issues/138

**Comment by lukebakken** [comment]
@jaredmorrow checking all that now, thanks for the pointer:

https://github.com/basho/yokozuna/issues/387

**Comment by lukebakken** [comment]
@jaredmorrow - FYI, on Ubuntu, `platform_base_dir` has `riak:riak` ownership, while on FreeBSD 10 it's `root:wheel`

**Comment by jaredmorrow** [comment]
@lukebakken So just confirming, this never got fixed in Yoko correct?

**Comment by lukebakken** [comment]
@jaredmorrow unfortunately the PR is still open.
