### ISSUE TITLE
Upgrading Riak and basho_patches

### ISSUE THREAD

**Issue by lukebakken** [basho/node_package#160]
When Riak is upgraded via a package manager, the `basho-patches` directory is left alone. Frequently, a Riak user will overlook the need to empty out the custom `.beam` files that potentially reside here.

This issue is to discuss whether or not to clean up this directory on upgrade. Perhaps on a `1.X.Y` to `1.X.Y+1` upgrade the directory is unchanged, but a `1.X` to `1.X+1` or `1.X` to `2.Y` the directory is cleaned up.

**Comment by jaredmorrow** [comment]
This is a tough one.  The only thing I can think of if finding a way to warn the user.  I'd really hate to remove a patch that wasn't affected by an upgrade.

**Comment by jaredmorrow** [comment]
Definitely a good thing to think about though.
