### ISSUE TITLE
Issue with packagecloud.io [JIRA: TOOLS-95]

### ISSUE THREAD

**Issue by lukebakken** [basho/node_package#182]
http://lists.basho.com/pipermail/riak-users_lists.basho.com/2015-March/016982.html

I want to report again a problem I have with packagecloud.io. Every time I do `aptitude update` I get a hit as if a new version of Riak is available (that is not)... and I have to re-install Riak to a version I already have.

I just did an "aptitude safe-upgrade" and upgraded Riak to version 2.0.5 (latest):

```
# aptitude safe-upgrade
The following packages will be upgraded: 
  ... ... ... riak ... ... ... ... ... ...
[...]
Unpacking riak (2.0.5-1) over (2.0.1) ...
[...]

# riak version
2.0.5

# aptitude update
Hit https://packagecloud.io trusty InRelease
Hit https://packagecloud.io trusty/main Sources
Hit https://packagecloud.io trusty/main amd64 Packages
Hit https://packagecloud.io trusty/main i386 Packages

# aptitude safe-upgrade
The following packages will be upgraded: 
  riak 
1 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/55.4 MB of archives. After unpacking 0 B will be used.
Do you want to continue? [Y/n/?]
```

If i select Y i get the following:

```
Unpacking riak (2.0.5-1) over (2.0.5-1) ...
```

and every time I check for updates, "riak" comes as requiring an update although is not true. How to fix that? makes no sense it continues coming as needing to be upgraded when is the same exact version.

**Comment by gcymbalski** [comment]
Turns out that this was an issue with the index generated by Packagecloud- Julio's put fixes in place to prevent it from happening again, and we're good! Just confirmed that it's behaving as normal on the platforms affected.

**Comment by Basho-JIRA** [comment]
[~gcymbalski], can this be closed? 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment]
Yep! 

**_[posted via JIRA by Greg Cymbalski]**_
