### ISSUE TITLE
If possible, don't start riak by default on install

### ISSUE THREAD

**Issue by evanmcc** [basho/node_package#26]
It leaves stale rings around, which then have to be deleted for anything to work, which is kind of non-obvious.

This is a kind of hacky way to do it for debs:

http://ubuntuforums.org/showthread.php?t=856815

Will look into it more tomorrow.

**Comment by nathanaschbacher** [comment]
Yeah, it's something of a mess.  Ideally something like MySQL's deb configuration wizard for ring size, node name, and possibly a few other config items would be awesome.  At a minimum just don't auto-start the service through upstart if possible.

**Comment by jaredmorrow** [comment]
Riak doesn't use node_package for its packaging config and Riak also doesn't start on install that I've ever seen live or seen in testing.  Can someone provide a reproducible use case I can see that does this?

**Comment by evanmcc** [comment]
@nathanaschbacher I know you were doing a lot of cloud provider settings, do you mind letting us know who is and isn't doing this (privately is likely better) and we'll let them know to fix it?

**Comment by nathanaschbacher** [comment]
I'm not sure I follow what you mean exactly.  You mean which cloud providers this is a problem with?  My issue was with the default Ubuntu server package when installing it locally under VMware ESXI v5.1

As soon as the package installs using dpkg -i, it starts the Riak process for the first time, I assume because of the upstart script.

**Comment by jaredmorrow** [comment]
We don't provide a upstart script with the RIak package, so I think Evan was curious what was starting RIak.   The package does no such thing in the postinst script.

**Comment by nathanaschbacher** [comment]
Jared you're correct, I realize the problem we're having now.  Riak is packaged to install an upstart service, but it doesn't start it upon installation.

What's happening for us is that we have a template VM in development that includes a base install of the Riak .deb and when we shutdown that VM, saved it as a template, and then bring up new VM's by cloning it the riak service starts for the first time upon that VM booting.

Which then means we're having to configure the riak app.config and vm.args files, wipe out the /var/lib/riak/ring directory, and restart the service.
