### ISSUE TITLE
init scripts are not LSB compliant

### ISSUE THREAD

**Issue by jsmartin** [basho/node_package#31]
The init scripts for riakcs & stanchion are not LSB compliant.  The biggest part missing is a "status" option.  The status option should tell you where the daemon is running or not.

It could be added to the init script like:

```
status() {
    RETVAL=`su - stanchion -c "$DAEMON ping"`
    [ "$RETVAL" = "pong" ] && echo $"$NAME is running..." && return 0
    echo $"$NAME is stopped"
    return 3
}


case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart)
  stop
  start
  ;;
  status)
        status
        ;;
  ping)
  $DAEMON ping || exit $?
        ;;
  *)
  echo $"Usage: $0 {start|status|stop|restart|ping}"
  exit 1
```

This also gives a good outline on LSB init script compliance:

http://linux-ha.org/wiki/LSB_Resource_Agents

The biggest thing we gain for fixing it up is that our products become easier to implement in a lot of configuration management tools (chef, puppet, ansible) and other things that depend on LSB compliance.  There are always work arounds to get passed our non-compliancy, but I think we'd make the experience that much better if we didn't have to tell our customers to work around it.

**Comment by jaredmorrow** [comment]
Fixed
