### ISSUE TITLE
Default Log Path on Debain is not Right 

### ISSUE THREAD

**Issue by densone** [basho/node_package#32]
When installing RiakCS on debian or Ubuntu, the lager log locations are broken (not sure if that's the right term), but it's not optimal.   

Examples: 
          {handlers, [
                      {lager_console_backend, info},
                      {lager_file_backend, [
                                            {"./log/error.log", error, 10485760, "$D0", 5},
                                            {"./log/console.log", info, 10485760, "$D0", 5}
                                           ]}
                     ]},

```
      %% Whether to write a crash log, and where.
      %% Commented/omitted/undefined means no crash logger.
      {crash_log, "./log/crash.log"},
```

**Comment by jaredmorrow** [comment]
Fixed
