### ISSUE TITLE
riak-cs-ee_1.3.1-1_amd64.deb does not include riak_repl_pb_api and so on

### ISSUE THREAD

**Issue by kuenishi** [basho/node_package#48]
I am testing riak-cs-ee with its MDC replication but it didn't work - looks like something's wrong.

with develop branch of Riak CS:

```
$ make package RELEASE=dev-1.3.1 RIAK_CS_EE_DEPS=true
```

and the created deb package doesn't include riak_repl_pb_api directory and so on within its lib.

**Comment by jaredmorrow** [comment]
Yes, this is indeed a huge bug and I need to figure out how to fix it.  I will actually move this to riak_cs because it will need to be fixed in that context.
