### ISSUE TITLE
Investigate shipping configuration to increase open files ulimit [JIRA: TOOLS-477]

### ISSUE THREAD

**Issue by jaredmorrow** [basho/node_package#55]
Users have expressed the interest in wanting the packages to automatically increase the open files limit by setting up files in '/etc/security/limits.d/'.  We should at least investigate the possibility and pro/cons of this solution.

We at least already have the {{ulimit_warn}} variable to simply set those limits the same to avoid warnings on linux.

**Comment by davidmweber** [comment]
I can suggest adding a term like `LimitNOFILE=70000` to the `[Service]` section of `/lib/systemd/system/riak.service`. This is equivalent to `ulimit -f 70000`. You can get some more details here: http://unix.stackexchange.com/a/345596

**Comment by davidmweber** [comment]
While you are looking at this, you should add `systemcfg enable riak` to the postinst script.

**Comment by jaredmorrow** [comment]
Since this was filed in '13 and no one is working on `node_package` anymore, I'm closing this.
