### ISSUE TITLE
Add support for FreeBSD pkg tool

### ISSUE THREAD

**Issue by hectcastro** [basho/node_package#90]
Filed on behalf of Bartlomiej Rutkowski:

FreeBSD introduced new `pkg` tool to replace old `pkg_add`, `pkg_delete`, etc. The new tool is recommended (yet not default) in FreeBSD 9.1 and is going to be the default in FreeBSD 9.2 (out in few days).

Once a user decides to switch to new `pkg` tool, the old package database will be converted to the new format, and old `pkg_*` tools can't be used anymore. The current Riak package fails using the new tool:

```
root@riak-dev:/root # ls -la riak-1.4.2-FreeBSD-amd64.tbz 
-rw-r--r-- 1 root wheel 32955171 Aug 30 00:40 riak-1.4.2-FreeBSD-amd64.tbz 
root@riak-dev:/root # uname -a 
FreeBSD riak-dev 9.1-RELEASE FreeBSD 9.1-RELEASE #0 r243825: Tue Dec 4 09:23:10 UTC 2012 root@farrell.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC amd64 
root@riak-dev:/root # pkg add riak-1.4.2-FreeBSD-amd64.tbz 
pkg: riak-1.4.2-FreeBSD-amd64.tbz is not a valid package: no manifest found 

Failed to install the following 1 package(s): riak-1.4.2-FreeBSD-amd64.tbz 
root@riak-dev:/root # 
```

The same is true for packages with Riak 1.4.1 and 1.4. More information about new `pkg` tools:
- http://www.freebsd.org/doc/handbook/pkgng-intro.html
- https://wiki.freebsd.org/pkgng

**Comment by jaredmorrow** [comment]
I will begin investigating this, thanks @hectcastro and Bartlomiej Rutkowski

**Comment by lukebakken** [comment]
Resources:
- https://wiki.freebsd.org/pkgng
- https://github.com/freebsd/pkg

**Comment by jaredmorrow** [comment]
This has been done in #128
