### ISSUE TITLE
Outdated reference to OpenSSL dependency

### ISSUE THREAD

**Issue by hectcastro** [basho/node_package#91]
Filed on behalf of Bartlomiej Rutkowski:

The Riak 1.4.2 package requires OpenSSL 1.0.0.1_7, which is no longer available in ports. In order to fix that, the package needs to be recompiled each time the OpenSSL port is being updated or instructions in Riak's FreeBSD installation documentation need to mention `libmap.conf` to map missing libraries to existing ones.

In the following example, the system has OpenSSL 1.0.0.1_8:

```
root@riak-dev:/root # cat /etc/libmap.conf 
libcrypto.so.7  libcrypto.so.8 
libssl.so.7 libssl.so.8 
root@riak-dev:/root # 
```

No other step is necessary, as the system will evaluate `libmap.conf` during each execution.

Note that this solution, while stable, may lead to issues when user map versions of libs that are not backwards compatible.

**Comment by lukebakken** [comment]
@roooms @jaredmorrow FYI this still applies to pre4.

**Comment by jaredmorrow** [comment]
Yeah, I haven't had any time yet to actually do my 2.0 tasks since I've been so busy testing all the major features for people.  I guess we'll have to punt on some of these platform fixes until after Ricon/tech-preview.

**Comment by lukebakken** [comment]
This is the `/etc/libmap.conf` from my 9.1 system:

```
[vagrant@FREEBSD-91-YZTEST-0 /vagrant/riak-data-loader]$ cat /etc/libmap.conf
libcrypto.so.8  libcrypto.so.7
libssl.so.8     libssl.so.7
```

**Comment by jaredmorrow** [comment]
This should be fixed in recent pre's by building on my 9.2 builder that didn't have additional openssl installed outside of the default.

@hectcastro @lukebakken Try any recent package

**Comment by hectcastro** [comment]
This appears to work for me on 9.2 using the 1.4.7 package. Although, admittedly, I'm a FreeBSD noob.

**Comment by lukebakken** [comment]
I just updated my FreeBSD 9.1 vms to 9.2, removed `/etc/libmap.conf`, and 2.0.0pre10 started up just fine.
